org.gradle.jvmargs=-Xmx2560m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8
org.gradle.workers.max=2
org.gradle.parallel=false
org.gradle.daemon=false
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false
android.builtInKotlin=false
android.newDsl=false

# Fix multi-drive (C:\ pub cache vs D:\ project) Kotlin daemon relative path bug
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

systemProp.http.connectionTimeout=180000
systemProp.http.socketTimeout=180000
systemProp.https.connectionTimeout=180000
systemProp.https.socketTimeout=180000

# Increase Dart VM heap for large kernel snapshot compilation
systemProp.DART_VM_OPTIONS=--heap-growth-ratio=1.5 --old-gen-heap-size=4096
