org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=false
android.builtInKotlin=false
android.newDsl=false

# Fix multi-drive (C:\ pub cache vs D:\ project) Kotlin daemon relative path bug
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false

systemProp.http.connectionTimeout=180000
systemProp.http.socketTimeout=180000
systemProp.https.connectionTimeout=180000
systemProp.https.socketTimeout=180000
